version: '3.8'

services:

  web:
    build: ./
    command: >
      sh -c "
      alembic upgrade head &&
      psql postgres://postgres:postgres@db:5432/db < /docker-entrypoint-initdb.d/seed_data.sql &&
      uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
      "
    volumes:
      - ./:/usr/src/app
      - ./seed_data.sql:/docker-entrypoint-initdb.d/seed_data.sql
    ports:
      - 8000:8000
    environment:
      - APP_NAME=Cats_exhibition
      - APP_VERSION=0.1.0
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/db
    depends_on:
      - db

  db:
    image: postgres:15.3
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db