[tool.flake8]
max-line-length = 88
exclude = [
    ".git",
    "__pycache__",
    "venv",
    "tests/",
    "migrations/",
    "app/core/base.py",
]
[tool.pytest.ini_options]
pythonpath = [
    ".", "src",
]
asyncio_mode="auto"
